/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _q3vm_objc_example_include_private_h__
#define _q3vm_objc_example_include_private_h__

/* no headers */

#endif
