/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _q3vm_objc_example_import_h__
#define _q3vm_objc_example_import_h__

# import <MulleObjC/MulleObjC.h>   // MulleObjC

#endif
