# cmake/_Dependencies.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   message( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

if( NOT Q3VM_OBJC_EXAMPLE_LIBRARY)
   find_library( Q3VM_OBJC_EXAMPLE_LIBRARY NAMES ${CMAKE_STATIC_LIBRARY_PREFIX}MulleObjC${CMAKE_STATIC_LIBRARY_SUFFIX} MulleObjC)
   message( STATUS "Q3VM_OBJC_EXAMPLE_LIBRARY is ${Q3VM_OBJC_EXAMPLE_LIBRARY}")

   # the order looks ascending, but due to the way this file is read
   # it ends up being descending, which is what we need
   if( Q3VM_OBJC_EXAMPLE_LIBRARY)
      set( ALL_LOAD_DEPENDENCY_LIBRARIES
         ${ALL_LOAD_DEPENDENCY_LIBRARIES}
         ${Q3VM_OBJC_EXAMPLE_LIBRARY}
         CACHE INTERNAL "need to cache this"
      )
      # temporarily expand CMAKE_MODULE_PATH
      get_filename_component( _TMP_Q3VM_OBJC_EXAMPLE_ROOT "${Q3VM_OBJC_EXAMPLE_LIBRARY}" DIRECTORY)
      get_filename_component( _TMP_Q3VM_OBJC_EXAMPLE_ROOT "${_TMP_Q3VM_OBJC_EXAMPLE_ROOT}" DIRECTORY)

      # search for DependenciesAndLibraries.cmake to include
      foreach( _TMP_Q3VM_OBJC_EXAMPLE_NAME "MulleObjC")
         set( _TMP_Q3VM_OBJC_EXAMPLE_DIR "${_TMP_Q3VM_OBJC_EXAMPLE_ROOT}/include/${_TMP_Q3VM_OBJC_EXAMPLE_NAME}/cmake")
         # use explicit path to avoid "surprises"
         if( EXISTS "${_TMP_Q3VM_OBJC_EXAMPLE_DIR}/DependenciesAndLibraries.cmake")
            unset( Q3VM_OBJC_EXAMPLE_DEFINITIONS)
            list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_Q3VM_OBJC_EXAMPLE_DIR}")
            # we only want top level INHERIT_OBJC_LOADERS, so disable them
            if( NOT NO_INHERIT_OBJC_LOADERS)
               set( NO_INHERIT_OBJC_LOADERS OFF)
            endif()
            list( APPEND _TMP_INHERIT_OBJC_LOADERS ${NO_INHERIT_OBJC_LOADERS})
            set( NO_INHERIT_OBJC_LOADERS ON)
            #
            include( "${_TMP_Q3VM_OBJC_EXAMPLE_DIR}/DependenciesAndLibraries.cmake")
            #
            list( GET _TMP_INHERIT_OBJC_LOADERS -1 NO_INHERIT_OBJC_LOADERS)
            list( REMOVE_AT _TMP_INHERIT_OBJC_LOADERS -1)
            #
            list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_Q3VM_OBJC_EXAMPLE_DIR}")
            set( INHERITED_DEFINITIONS
               ${INHERITED_DEFINITIONS}
               ${Q3VM_OBJC_EXAMPLE_DEFINITIONS}
               CACHE INTERNAL "need to cache this"
            )
            break()
         else()
            message( STATUS "${_TMP_Q3VM_OBJC_EXAMPLE_DIR}/DependenciesAndLibraries.cmake not found")
         endif()
      endforeach()

      # search for objc-loader.inc in include directory
      # this can be turned  off (see above)
      if( NOT NO_INHERIT_OBJC_LOADERS)
         foreach( _TMP_Q3VM_OBJC_EXAMPLE_NAME "MulleObjC")
            set( _TMP_Q3VM_OBJC_EXAMPLE_FILE "${_TMP_Q3VM_OBJC_EXAMPLE_ROOT}/include/${_TMP_Q3VM_OBJC_EXAMPLE_NAME}/objc-loader.inc")
            if( EXISTS "${_TMP_Q3VM_OBJC_EXAMPLE_FILE}")
               set( INHERITED_OBJC_LOADERS
                  ${INHERITED_OBJC_LOADERS}
                  ${_TMP_Q3VM_OBJC_EXAMPLE_FILE}
                  CACHE INTERNAL "need to cache this"
               )
               break()
            endif()
         endforeach()
      endif()
   else()
      message( FATAL_ERROR "Q3VM_OBJC_EXAMPLE_LIBRARY was not found")
   endif()
endif()
